### ISSUE TITLE
[Suggestion] Better URL Routes

### ISSUE THREAD

**Issue by ellemedit** [CloudBreadProject/CloudBread#24]
Hi. I'm developer signed up CB camp. I guess CloudBread's RESTful API routes can be improved for better immediacy. Let me suggest below.
# API Route Rule
## CRUD

API to create, read, update and delete resources.
### Find Resources

Method: GET

`/v3/:resources`
`/v3/:resources/:resourceID`
`/v3/:resources/:resourceID/:children`
`/v3/:resources/:resourceID/:children/:childID`
### Create Resource

Method: POST

`/v3/:resources`
`/v3/:resources/:resourceID/:children`
### Update Resources

Method: PUT, PATCH (_PUT is dominating but PATCH is also nice_)

`/v3/:resources`
`/v3/:resources/resourceID`
`/v3/:resources/:resourceID/:children`
`/v3/:resources/:resourceID/:children/:childID`
### Delete Resources

Method: DELETE

`/v3/:resources`
`/v3/:resources/:resourceID`
`/v3/:resources/:resourceID/:children`
`/v3/:resources/:resourceID/:children/:childID`
## Conditions

Sometimes, requestements need conditions such as sorting, limiting, skipping and filtering resources.
### Skipping

``` json
{
  "skip": 40,
  "skip": 140
}
```
### Limiting

``` json
{
  "limit": 30,
  "limit": 10
}
```
### Sorting

``` json
{
  "sort": "createdAt desc",
  "sort": "username asc, updatedAt desc",
  "sort": {
    "field": "createdAt",
    "method": "desc"
  },
  "sort": [
    {
      "field": "username",
      "method": "asc"
    }, {
      "field": "updatedAt",
      "method": "desc"
    }
  ],
  "sort": [
    "username asc",
    "updatedAt desc"
  ]
}
```
### Filtering

``` json
{
  "where": [
    {
      "field": "balance",
      "operator": ">",
      "value": 4000
    }, {
      "field": "level",
      "operator": "<",
      "value": 20
    }, {
      "field": "username",
      "operator": "contain",
      "value": "BlahBlah"
    }
  ],
  "where": {
    "balance": {
      "operator": ">",
      "value": 4000
    },
    "level": {
      "operator": "<",
      "value": 20
    },
    "username": {
      "operator": "contain",
      "value": "BlahBlah"
    }
  },
  "where": {
    "balance": [">", 4000],
    "level": ["<", 20],
    "username": ["contain", "BlahBlah"]
  }
}
```
## Replacement Examples

`/api/CBComSelMember` => `/v3/members/:memberID`
`/api/CBComUdtItemList1` => `/v3/members/:memberID/items1`
`/api/CBSelGiftItemToMe` => `/v3/members/:memberID/gifts`

Thank you!

**Comment by CloudBreadPaPa** [comment]
Hello, Beingbook.
First of all, I appreciate your suggestion issue.
This issue is one of my top mind issue will be fixed in next version change, definitely.
As we discussed about the next version planning meeting, it should be the on top of priority list.

Thanks and we will discuss about it in private.
