### ISSUE TITLE
cloudbread unity sdk generate error

### ISSUE THREAD

**Issue by tenvolts** [CloudBreadProject/CloudBread#51]
[http://xxxxxxxxxx.azurewebsites.net/api/CBInsRegMember] - 500 Internal Server Error
UnityEngine.Debug:LogWarning(Object)
CloudBread.CBPostman:DirectWWW(WWW, Action`1) (at Assets/CloudBread/Editor/CBPostman.cs:460)
CloudBread.CBPostman:RequestPostmanTest(String, String, String, Action`1) (at Assets/CloudBread/Editor/CBPostman.cs:422)
CloudBread.CBPostman:DrawBodyRight() (at Assets/CloudBread/Editor/CBPostman.cs:212)
CloudBread.CBPostman:DrawBody() (at Assets/CloudBread/Editor/CBPostman.cs:70)
CloudBread.CBPostman:OnGUI() (at Assets/CloudBread/Editor/CBPostman.cs:34)
UnityEditor.DockArea:OnGUI()

라고 뜨면서 프로토콜 폴더에 C# 스크립트가 생성되지 않습니다.

**Comment by CloudBreadPaPa** [comment]
working on with style0912

**Comment by CloudBreadPaPa** [comment]
it was server configuration issue of encryption. 
changed web.config(azure app configuration) file and fixed it.
case closed.
